.ONESHELL:
CC=gcc
CFLAGS=-I.
ALL_T= 
SUB_T= 
OPTIMIZATION_LEVEL=-O3
SDL2_LIBS= -lSDL2 -lSDL2_mixer -lSDL2main
OTHER_LIBS= -lm
ALL_LIBS= $(SDL2_LIBS) $(OTHER_LIBS)
all: $(ALL_T) $(SUB_T)
clean:
	rm -f $(ALL_T)
	rm -f *.exe